/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepositsRouteImport } from './routes/deposits'
import { Route as LiquidationsRouteImport } from './routes/liquidations'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsRoute = DepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidationsRoute = LiquidationsRouteImport.update({
  id: '/liquidations',
  path: '/liquidations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deposits' | '/liquidations' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deposits' | '/liquidations' | '/login'
  id: '__root__' | '/' | '/deposits' | '/liquidations' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepositsRoute: typeof DepositsRoute
  LiquidationsRoute: typeof LiquidationsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits': {
      id: '/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidations': {
      id: '/liquidations'
      path: '/liquidations'
      fullPath: '/liquidations'
      preLoaderRoute: typeof LiquidationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepositsRoute: DepositsRoute,
  LiquidationsRoute: LiquidationsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
