/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepositsRouteImport } from './routes/deposits'
import { Route as LiquidationsRouteImport } from './routes/liquidations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ParametersRouteImport } from './routes/parameters'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsRoute = DepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidationsRoute = LiquidationsRouteImport.update({
  id: '/liquidations',
  path: '/liquidations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersRoute = ParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/parameters': typeof ParametersRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/parameters': typeof ParametersRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deposits': typeof DepositsRoute
  '/liquidations': typeof LiquidationsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/parameters': typeof ParametersRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deposits'
    | '/liquidations'
    | '/login'
    | '/operations'
    | '/parameters'
    | '/reconciliation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deposits'
    | '/liquidations'
    | '/login'
    | '/operations'
    | '/parameters'
    | '/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/deposits'
    | '/liquidations'
    | '/login'
    | '/operations'
    | '/parameters'
    | '/reconciliation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepositsRoute: typeof DepositsRoute
  LiquidationsRoute: typeof LiquidationsRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  ParametersRoute: typeof ParametersRoute
  ReconciliationRoute: typeof ReconciliationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits': {
      id: '/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidations': {
      id: '/liquidations'
      path: '/liquidations'
      fullPath: '/liquidations'
      preLoaderRoute: typeof LiquidationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters': {
      id: '/parameters'
      path: '/parameters'
      fullPath: '/parameters'
      preLoaderRoute: typeof ParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepositsRoute: DepositsRoute,
  LiquidationsRoute: LiquidationsRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  ParametersRoute: ParametersRoute,
  ReconciliationRoute: ReconciliationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
