/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExposureRouteImport } from './routes/exposure'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as IntakeIntakeIdRouteImport } from './routes/intake.$intakeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposureRoute = ExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIntakeIdRoute = IntakeIntakeIdRouteImport.update({
  id: '/intake/$intakeId',
  path: '/intake/$intakeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exposure': typeof ExposureRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/intake/$intakeId': typeof IntakeIntakeIdRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exposure': typeof ExposureRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/intake/$intakeId': typeof IntakeIntakeIdRoute
  '/intake': typeof IntakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exposure': typeof ExposureRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/intake/$intakeId': typeof IntakeIntakeIdRoute
  '/intake/': typeof IntakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exposure'
    | '/inventory'
    | '/login'
    | '/intake/$intakeId'
    | '/intake/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exposure'
    | '/inventory'
    | '/login'
    | '/intake/$intakeId'
    | '/intake'
  id:
    | '__root__'
    | '/'
    | '/exposure'
    | '/inventory'
    | '/login'
    | '/intake/$intakeId'
    | '/intake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExposureRoute: typeof ExposureRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  IntakeIntakeIdRoute: typeof IntakeIntakeIdRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposure': {
      id: '/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof ExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$intakeId': {
      id: '/intake/$intakeId'
      path: '/intake/$intakeId'
      fullPath: '/intake/$intakeId'
      preLoaderRoute: typeof IntakeIntakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExposureRoute: ExposureRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  IntakeIntakeIdRoute: IntakeIntakeIdRoute,
  IntakeIndexRoute: IntakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
